version: '3.5'

services:
  db_index:
    container_name: db_index
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=index_test
    image: postgres:14.3-alpine